# src/main/resources/config.yml

growth-times:
  wheat: 60
  carrots: 60
  potatoes: 60
  beetroots: 60
  oak_sapling: 300
  birch_sapling: 300
  spruce_sapling: 300
  jungle_sapling: 300
  acacia_sapling: 300
  dark_oak_sapling: 300
  debug: false
