# src/main/resources/config.yml

update-interval-seconds: 60 # default is 60
maintenance-interval: 600
vacuum-interval: 10800

growth-times:
  wheat: 1200
  carrots: 600
  potatoes: 600
  beetroots: 600
  nether_wart: 2400
  sweet_berry_bush: 400
  cocoa: 600
  pumpkin_stem: 1200
  melon_stem: 1200
  kelp: 1500
  sugar_cane: 1600
  cactus: 1200
  oak_sapling: 1200
  birch_sapling: 1200
  spruce_sapling: 1200
  jungle_sapling: 1200
  acacia_sapling: 1200
  dark_oak_sapling: 1200
  cherry_sapling: 1200
  bamboo_sapling: 800
  mangrove_propagule: 1200

# default is 30% change to spawn the Tall Mangrove Tree
TALL_MANGROVE_CHANGE: 30

# The chance (0.0 to 1.0) for a bee hive to be added when a tree grows from a sapling
# The default 0.05 gives a 5% chance for the bee hive to be added
bee-hive-chance: 0.05

# The minimum and maximum number of bees per hive
min-bees-per-hive: 1
max-bees-per-hive: 3

debug: false # set to true to enable this, if you would like to see the debugging values