name: eternalharvest
version: '1.0'
main: org.rufftrigger.eternalharvest.Main
description: EternalHarvest is a Bukkit/Spigot plugin designed to simulate the growth of plants (crops, saplings) even when the server is offline or the chunk is unloaded.
api-version: '1.16'
author: RuffTrigger